AWSTemplateFormatVersion: "2010-09-09"
Description: The template is ec2

Parameters:
  SystemName:
    Type: String
    Default: MSP-Test

  EC2ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-kernel-5.10-hvm-x86_64-gp2


Resources:

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${SystemName}-ec2-sg
      GroupDescription: !Sub ${SystemName}-ec2-sg
      VpcId:
        Fn::ImportValue: !Sub ${SystemName}-vpc-VPC
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-ec2-sg

  EC2SecurityGroupIngressSSH:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref EC2SecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: 0.0.0.0/0    
  
  EC2SecurityGroupIngressHttp:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref EC2SecurityGroup
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      CidrIp: 0.0.0.0/0

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref EC2ImageId
      InstanceType: t2.micro
      KeyName: my-key
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId:
            Fn::ImportValue: !Sub ${SystemName}-vpc-PublicSubnetA
          GroupSet:
            - !Ref EC2SecurityGroup

      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum update -y
          sudo yum -y install httpd
          sudo systemctl start httpd.service
          sudo systemctl enable httpd.service

      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-EC2
